### ISSUE TITLE
ERROR: The Compose file is invalid because: services.traefik.ports is invalid

### ISSUE THREAD

**Issue by metal450** [crazy-max/docker-firefox-syncserver#1]
Thanks a ton for putting this together :) Trying to get it up & running, but it looks like "docker-compose up" is generating the error:

_ERROR: The Compose file './docker-compose.yml' is invalid because:
services.traefik.ports is invalid: Invalid port "{'target': 443, 'protocol': 'tcp', 'mode': 'host', 'published': 443}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.traefik.ports contains an invalid type, it should be a string, or a number
services.traefik.ports is invalid: Invalid port "{'target': 80, 'protocol': 'tcp', 'mode': 'host', 'published': 80}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.traefik.ports contains an invalid type, it should be a string, or a number_

**Comment by crazy-max** [comment]
Hi @metal450, i have updated the compose file ;)
Thanks for your support

**Comment by metal450** [comment]
Sweet, thanks for the quick fix!
