### ISSUE TITLE
Doesn't launch on a raspberry pi 3B +

### ISSUE THREAD

**Issue by arond1** [crazy-max/docker-firefox-syncserver#11]
### Behaviour
command run as root :
docker run -p 5000:5000 --name firefox_sync -e TZ="Europe/Paris" -e FF_SYNCSERVER_SECRET="1up3rS7zptn" -v /data:/data crazymax/firefox-syncserver:latest

problem : 
standard_init_linux.go:207: exec user process caused "exec format error"

#### Steps to reproduce this issue

1. launch this command on a raspberry pi 3 model B +
2.
3.

#### Expected behaviour
container launching 

#### Actual behaviour

standard_init_linux.go:207: exec user process caused "exec format error"
### Configuration

* Docker version (type `docker --version`) :Docker version 18.09.0, build 4d60db4
* Platform (Debian 9, Ubuntu 18.04, ...) : Raspian

**Comment by crazy-max** [comment]
This image only handles `linux/amd64`. Feel free ton open a PR to add support for ARM architecture.

**Comment by crazy-max** [comment]
@arond1 [Multi-platform](https://github.com/crazy-max/docker-firefox-syncserver#multi-platform-image) is now supported for this image.
