### ISSUE TITLE
Mariadb support

### ISSUE THREAD

**Issue by BobWs** [crazy-max/docker-firefox-syncserver#12]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour
Does this image support mariadb as an alternitave database? I can seem to get it to work with maraidb.
> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

* Docker version (type `docker --version`) :
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) : 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> Container logs (set FF_SYNCSERVER_LOGLEVEL to debug if applicable)
```

**Comment by crazy-max** [comment]
Yes MySQL/MariaDB is supported. See [this comment](https://github.com/crazy-max/docker-firefox-syncserver/issues/8#issuecomment-492148447) for more info.

**Comment by BobWs** [comment]
Thanks! 
mysql vs pymysql....That was it for me too.
Mabybe you could at this to the documentation. 

Thanks for the help!

**Comment by crazy-max** [comment]
@BobWs Yes I will add a note about this, thanks.
