### ISSUE TITLE
ConnectionError: Failed to GET https://api.accounts.firefox.com/.well-known/browserid.

### ISSUE THREAD

**Issue by BobWs** [crazy-max/docker-firefox-syncserver#13]
### 
#### Steps to reproduce this issue

1. Hi I'm suddenly getting an error on my syncserver and sync doesn't work anymore.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead  

### Configuration 

* Docker version (type `docker --version`) : 18.0.9
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) : Synology 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```

ConnectionError: Failed to GET https://api.accounts.firefox.com/.well-known/browserid. Reason:
 HTTPSConnectionPool(host='api.accounts.firefox.com', port=443): Max retries exceeded with url: 
/.well-known/browserid (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f02a004a0d0>: 
Failed to establish a new connection: [Errno -3] Try again',)) | stderr

-- | --
```

**Comment by crazy-max** [comment]
Same issue as #9, check your host

**Comment by BobWs** [comment]
I have read that before posting but his problem was not on a Synology NAS as host, so I don’t know if it is related.

**Comment by BobWs** [comment]
Unfortunately it isn't working for the command as suggested `apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make` in #9. I keep getting an error `command not found`
I guess this isn't the right command for docker Synology. Do you have any sugguestions how to fix this for my specific case?

Docker version 18.09.0
Host Synology NAS DSM version 6.2.2

**Comment by ilovepancakes95** [comment]
I am having the exact same issue mentioned above and in #9 using Docker on Synology. How would I go about resolving using those commands since apk doesn't applying to Synology? Or is there a way to get those dependancies installed as part of the docker image? Really excited to get this working hopefully....
