### ISSUE TITLE
Doesn’t sync with iOS only with desktop 

### ISSUE THREAD

**Issue by BobWs** [crazy-max/docker-firefox-syncserver#15]
Hi, 
I can’t seem to get the sync to work with iOS Firefox. It only works on the desktop (mac/windows). In iOS I also set the url to https://sync.mydomain/token/1.0/sync/1.5 but nothing happens no bookmarks are synced. I have also tried https://sync.mydomain/ but also nothing. 

I followed the steps as described here https://daniel-ziegler.com/computer/netzwerk/linux/2019/07/07/Firefox-Sync-iOS/

Do you have any ideas how to fix this?

**Comment by Section1977** [comment]
I have exactly the same problem
Please fix

**Comment by crazy-max** [comment]
@BobWs That doesn't look like an issue with this image itself and sorry I don't have time to help you if it isn't directly related to this Docker image. I suggest to open an issue on [mozilla-services/syncserver](https://github.com/mozilla-services/syncserver/issues) instead for this kind of problem. And also next time please open a proper [bug report](https://github.com/crazy-max/docker-firefox-syncserver/issues/new?template=bug_report.md).
