### ISSUE TITLE
[question] difference your image vs Mozilla official?

### ISSUE THREAD

**Issue by zilexa** [crazy-max/docker-firefox-syncserver#17]
Mozilla also allows you to pull in syncserver via their docker image: 
https://github.com/mozilla-services/syncserver
Is your better/easier/faster? 

Also, I noticed support for MariaDB/MySQL is available. I thought MariaDB is much better for large databases versus SQLite. Is there a good argument to use it for Firefox Syncserver?

**Comment by crazy-max** [comment]
@zilexa I think the main reason was the official image was not alpine-based, forwarding was not working and wsgi wrapper was a mess for gunicorn. And also missing features like multi-platform Docker image and log management.

**Comment by crazy-max** [comment]
And they don't create semantic releases on DockerHub. Only latest tag is updated at this time so this could break your installation if they push a breaking change like mozilla-services/syncserver#200.
Maybe they want to focus on the next [syncserver generation](https://github.com/mozilla-services/syncstorage-rs) :)
