### ISSUE TITLE
[request] Point to a secret key file instead of writing it in docker-compose.yml

### ISSUE THREAD

**Issue by zilexa** [crazy-max/docker-firefox-syncserver#18]
Currently the secret key itself needs to be given in an environmental variable. 
Please allow the ability to link to a file instead, which should contain the secret key. 

something like:
```
volumes: 
  - home/user/docker/firefox/secret:data/secret
```

**Comment by crazy-max** [comment]
Already available: https://github.com/crazy-max/docker-firefox-syncserver/blob/master/entrypoint.sh#L54

**Comment by zilexa** [comment]
Oh that's great thank you!!

**Comment by zilexa** [comment]
Pardon me for asking this, as I am already grateful for the image you have created. 
I couldn't find more details in the documentation from Mozilla and as I am not a pro yet with Docker, one last question:
Can I just use .txt file extension or no extension at all? This is how I have set it up now:
``
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FF_SYNCSERVER_PUBLIC_URL=https://firefox.mydomain.com
      - FF_SYNCSERVER_FORWARDED_ALLOW_IPS=*
      - FF_SYNCSERVER_SECRET_FILE=/data/secret/secret.txt
    volumes:
      - "${USERDIR}/docker/firefox-syncserver:/data"
```
and on the host the secret is in:
${USERDIR}/docker/firefox-syncserver/secret/secret.txt
