### ISSUE TITLE
Help with setup?

### ISSUE THREAD

**Issue by gaining** [crazy-max/docker-firefox-syncserver#3]
I need help setting this up. Forgive me for my lack of knowledge in docker, this is the first time I'm attempting to use it.

My configuration
Debian 9, nginx webserver, 4gb ram SBC, arm64

What I have installed which I think could help me get this done
- docker-ce 18.03.1, docker-compose 1.21.2, my own ssl keys and certificates from certbot (let's encrypt)
- I was able to run arm64v8/hello-world to see if it was successfully installed.

I noticed that you have traefik for let’ s encrypt. I already have certbot setup on my server so I think I'll be able to skip this.

What I hope to achieve:
- run own personal firefox sync server so I could access it at work, school, mobile or home using HTTPS.

Hypothetically, I have this network/server configuration
- everything IPV4
- router ip: 10.0.3.1
- server local ip: 10.0.3.50
- ddns from no-ip (reflects public ip): https://gaining7.ddns.net
- ports 80 and 443 are already in use in this server for other services so I’d rather use something different maybe 8080 and 8443
- home directory: /home/gaining
- firefox directory created for server

Questions: 
	-How should I go about configuring my docker-compose.yml file and how should I run it?
	-Should I forward port 5000 from my router?

I would greatly appreciate if you could guide me in setting this up. Thanks.

**Comment by crazy-max** [comment]
Sorry I don't have time to help you if it isn't directly related to this Docker image.
I suggest to post your question on reddit for this kind of stuff :

* [/r/selfhosted](https://reddit.com/r/selfhosted/)
* [/r/firefox](https://reddit.com/r/firefox/)
* [/r/docker](https://reddit.com/r/docker/)
* [/r/privacy](https://reddit.com/r/privacy/)

And have look here too :

* https://github.com/mozilla-services/syncserver
* http://moz-services-docs.readthedocs.io/en/latest/sync/
* http://moz-services-docs.readthedocs.io/en/latest/howtos/run-sync-1.5.html#asking-for-help
