### ISSUE TITLE
Use MySQL instead of SQLite (Feature request)

### ISSUE THREAD

**Issue by jerheij** [crazy-max/docker-firefox-syncserver#5]
Great work, got this Docker image working without any big issues! 

I had one question: does the Docker container support MySQL by default or does it need additional libraries for that? If so, maybe you could add the _sqluri_ as variable so you can use any supported SQL server in your configuration.

**Comment by crazy-max** [comment]
Should be ok now, check the CHANGELOG and thanks for your support!
